### ISSUE TITLE
Add Tests to Build Workflow

### ISSUE THREAD

**Issue by davidwesst** [fullstackmb/fullstackmb.github.io#6]
Tests should be included to validate the site using [Playwright](https://playwright.dev) and/or another testing framework for build logic tests.

## Tasks

- [x] Create tests
- [ ] ~~Create VSCode test task for running tests~~ (Removed from scope)
- [x] #14 (Created separate issue for this)

**Comment by paiziak-o** [comment]
What do you use for ci/cd? github actions or anything else?

**Comment by davidwesst** [comment]
Just GitHub workflows/actions. 👍

**Comment by paiziak-o** [comment]
do you want to run it for each PR? i just worrying the we may hit github run time limits.

**Comment by paiziak-o** [comment]
Here is base infrastructure for playwright https://github.com/fullstackmb/fullstackmb.github.io/pull/13, 

next steps add more tests and run it when via github actions
