### ISSUE TITLE
Generate the version number at base of home page

### ISSUE THREAD

**Issue by davidwesst** [fullstackmb/fullstackmb.github.io#8]
The version number displayed at the base of the home page (`index.liquid`) is static, but should be generated during build time. It should follow [Semver 2.0](https://[semver.org](https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions) Backusnaur Form Grammar , include be made up of version number in package.json and the shortened git commit hash.

Examples:
- 3.0.0-alpha+1a2b3c4
- 3.0.1+1a2s3d4

**Comment by paiziak-o** [comment]
do you want to update packages.json version every time when PR is merged to main?

**Comment by davidwesst** [comment]
No. The git commit should be calculated at build time, so no need for the packages.json to be updated.

The 3.0.0 part should only be updated when necessary. When is it necessary? Not sure yet. Still figuring that out.

**Comment by paiziak-o** [comment]
@davidwesst here is the PR https://github.com/fullstackmb/fullstackmb.github.io/pull/12

**Comment by davidwesst** [comment]
Resolved with PR #12
